# Generated by Django 4.1.5 on 2023-05-30 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_active_product_registered_at_seller_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='registered_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 30, 9, 30, 16, 514275)),
        ),
    ]
